// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_TCcoIsvy60cPNEUNorhTxgkR5CzgOU',
    appId: '1:467102573962:web:c9f6c8a41183230142d473',
    messagingSenderId: '467102573962',
    projectId: 'applever-todo',
    authDomain: 'applever-todo.firebaseapp.com',
    storageBucket: 'applever-todo.appspot.com',
    measurementId: 'G-C3VKS8J8S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmaVntztVb2f_h4ZNFrVD0S8y_XLWPp_I',
    appId: '1:467102573962:android:558ed136627f90cc42d473',
    messagingSenderId: '467102573962',
    projectId: 'applever-todo',
    storageBucket: 'applever-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZKttioyLV0Ree4D2mNsoKEDjaJyzoTfg',
    appId: '1:467102573962:ios:5f93c3c95b7c357842d473',
    messagingSenderId: '467102573962',
    projectId: 'applever-todo',
    storageBucket: 'applever-todo.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZKttioyLV0Ree4D2mNsoKEDjaJyzoTfg',
    appId: '1:467102573962:ios:acf7fe2809e3fff642d473',
    messagingSenderId: '467102573962',
    projectId: 'applever-todo',
    storageBucket: 'applever-todo.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
